# Generado por theme-changer — no editar directamente

general {
    col.active_border   = rgba(bd93f9ff) rgba(ff79c6ff) 45deg
    col.inactive_border = rgba(44475aaa)
}

decoration {
    shadow {
        color = rgba(000000aa)
    }
}

# Blur de capas
blurls = wlogout
blurls = rofi
