color0 #41484a
color1 #ffb4ab
color2 #abccd6
color3 #bcc9cd
color4 #d1c0e0
color5 #abccd6
color6 #bcc9cd
color7 #e3e2e3
color8 #8b9294
color9 #ffb4ab
color10 #abccd6
color11 #bcc9cd
color12 #d1c0e0
color13 #abccd6
color14 #bcc9cd
color15 #e3e2e3

cursor                #e3e2e3
cursor_text_color     #000000
background            #000000
foreground            #e3e2e3
selection_foreground  #c1c7ca
selection_background  #41484a
active_border_color   #abccd6
inactive_border_color #333a3c
url_color             #abccd6

active_tab_foreground   #14353d
active_tab_background   #abccd6
inactive_tab_foreground #c1c7ca
inactive_tab_background #333a3c
cursor_trail_color      #c1c7ca
