color0 #444654
color1 #ffb4ab
color2 #bac3ff
color3 #bbc3fb
color4 #fcaaff
color5 #bac3ff
color6 #bbc3fb
color7 #e3e1ec
color8 #8f8fa0
color9 #ffb4ab
color10 #bac3ff
color11 #bbc3fb
color12 #fcaaff
color13 #bac3ff
color14 #bbc3fb
color15 #e3e1ec

cursor                #e3e1ec
cursor_text_color     #000000
background            #000000
foreground            #e3e1ec
selection_foreground  #c5c5d6
selection_background  #444654
active_border_color   #bac3ff
inactive_border_color #363846
url_color             #bac3ff

active_tab_foreground   #001f90
active_tab_background   #bac3ff
inactive_tab_foreground #c5c5d6
inactive_tab_background #363846
cursor_trail_color      #c5c5d6
