color0 #484552
color1 #ffb4ab
color2 #c9bfff
color3 #c9c1ee
color4 #ffade3
color5 #c9bfff
color6 #c9c1ee
color7 #e5e1ea
color8 #938f9d
color9 #ffb4ab
color10 #c9bfff
color11 #c9c1ee
color12 #ffade3
color13 #c9bfff
color14 #c9c1ee
color15 #e5e1ea

cursor                #e5e1ea
cursor_text_color     #000000
background            #000000
foreground            #e5e1ea
selection_foreground  #c9c4d3
selection_background  #484552
active_border_color   #c9bfff
inactive_border_color #3a3744
url_color             #c9bfff

active_tab_foreground   #301c7e
active_tab_background   #c9bfff
inactive_tab_foreground #c9c4d3
inactive_tab_background #3a3744
cursor_trail_color      #c9c4d3
