format = """
$username$directory $git_branch\n$character """

[username]
show_always = true
style_user = "bold yellow"
format = "[$user]($style):"  # Colon after username

[directory]
style = "bold blue"
format = "[$path]($style)"  # No space before directory

[git_branch]
symbol = " *"  # No icon, just branch name
style = "bold purple"
format = "(($branch$git_status)($style))"  # Git status inside parentheses

[git_status]
style = "bold red"
format = "[ *]($style)"  # Red asterisk for uncommitted changes
conflicted = "[ *]($style)"
untracked = "[ *]($style)"
modified = "[ *]($style)"
staged = "[ *]($style)"
renamed = "[ *]($style)"
deleted = "[ *]($style)"

[character]
success_symbol = "[➜](bold white)"
error_symbol = "[➜](bold red)"
