format = """
$username$directory $git_branch\n$character """

[username]
show_always = true
style_user = "bold yellow"
format = "[$user]($style):"  # Colon after username

[directory]
style = "bold blue"
format = "[$path]($style)"  # No space before directory

[git_branch]
symbol = ""  
style = "bold red"
#format = "([$branch]($style))"  # Git status inside parentheses
format = '\([$branch]($style)\)'

[git_status]
style = "bold red"
format = "[ *]($style)"  # Red asterisk for uncommitted changes
conflicted = "[ *]($style)"
untracked = "[ *]($style)"
modified = "[ *]($style)"
staged = "[ *]($style)"
renamed = "[ *]($style)"
deleted = "[ *]($style)"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
